import { Inter } from "@next/font/google";
import { ForwardedHookForm } from "components/HookForm";
import Head from "next/head";
import { useCallback, useRef } from "react";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const hookformRef = useRef(null);

  const handleSubmit = useCallback(async (data) => {
    console.log("handlesubmit", data);
    const httpResponse = await fetch("/api/test", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        name: data.email,
        impact: data.impact,
        summary: data.summary,
        email: data.email,
        privacy: data.privacy,
      }),
    });
    const jsonResponse = await httpResponse.json();
    if (!jsonResponse.success) {
      hookformRef.current?.setErrors(jsonResponse.errors);
      return;
    }

    await new Promise((resolve) => setTimeout(resolve, 500));
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <ForwardedHookForm ref={hookformRef} onSubmitReady={handleSubmit} />
      </main>
    </>
  );
}
